[env]
AFFIRM_MISE_ACTIVE = "true"

[settings]
env_file = ".env"
disable_tools = ["npm", "pnpm", "yarn"]

[tools]
bun = { version = "1.3.9" }
node = { version = "24.13.1" }
rust = { version = "1.93.0" }

[tasks]
'start' = { run = "bun dev", description = "Start the development server" }
