[env]
AFFIRM_MISE_ACTIVE = "true"

[settings]
env_file = ".env"
disable_tools = ["npm", "pnpm", "yarn"]

[tools]
bun = { version = "1.3.8" }
claude = { version = "2.1.22" }
codex = { version = "0.92.0" }
gemini = { version = "0.26.0" }
node = { version = "24.13.0" }
rust = { version = "1.93.0" }

[tasks]
'start' = { run = "bun dev", description = "Start the development server" }
